name: Container build

on:
  push:
    branches:
      - main
    tags-ignore:
      - '*.*'

jobs:
  build-image:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout application-service source code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}
          registry: quay.io

      - name: Docker Build
        run: make docker-build

      - name: Docker Push
        run: make docker-push
